backend:
  name: github
  repo: "damongolding/next"
  branch: master

media_folder: "public/img"
public_folder: "/img"

site_domain : 2e327e60-5e53-40f6-8d7b-b64a561e7a65
base_url : https://api.netlify.com

show_preview_links: false

collections:
  - name: "Site" # Used in routes, e.g., /admin/collections/blog
    label: "Site" # Used in the UI
    files:
      - label: "Home"
        name: "Home"
        file: "data/foo.json"
        extension: json
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
