name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: [12.x] # Only run the 10.x build

    steps:
      - uses: actions/checkout@v2
        name: Uses Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run : npm install -g yarn 

      - name: Build Next
        run: |
          yarn install
          yarn build
          yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./out
