name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: [12.x] # Only run the 10.x build

    steps:
      - uses: actions/checkout@v2
      
      - uses: borales/actions-yarn@v2.0.0
        name : Yarn install
        with:
          cmd: install # will run `yarn install` command

      - uses: borales/actions-yarn@v2.0.0
        name : Yarn build
        with:
          cmd: build # will run `yarn install` command

      - uses: borales/actions-yarn@v2.0.0
        name : Yarn export
        with:
          cmd: export # will run `yarn install` command

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./out
